#15 Feat: 출석 API 구현
Leets-Official/Weeth-BE-Legacy pull request #21
Opened 2024-07-12 15:59 UTC by huncozyboy

## 1. 개발내용
출석 API 구현

## 2. 구현 세부사항
## **controller**

**AttendanceController**: 출석 관련 API 엔드포인트를 처리하는 컨트롤러로 성공 시나리오를 남기고,
서비스에서 예외를 처리하도록 구현했습니다
- `/api/attendance` 경로에 출석 관련 API를 매핑.
- `GET /api/attendance/meetings`: 모든 모임 정보 조회.
- `POST /api/attendance/check-in`: 출석하기 기능 구현.
- `GET /api/attendance/statistics/{userId}`: 출석률 통계 조회.
- `POST /api/attendance/penalty` : 패널티 기능 구현.

## **Dto**

- **RequestAttendance** : 사용자가 출석 요청을 보낼 때 필요한 데이터
attendanceCodeId: 출석 코드의 ID
userId: 사용자 ID
isAttend: 출석 여부

- **RequestPenalty** :  사용자가 패널티 기록 요청을 보낼 때 필요한 데이터
userId: 사용자 ID
description: 패널티 설명

- **RequestWeek** :  정기모임의 주차별 요청을 보낼 때 필요한 데이터

- **ResponseAttendance** : 

- **ResponseMeeting** : 정기모임 정보를 반환시 사용

- **ResponsePenalty** : 패널티 정보를 반환시 사용

- **ResponseStatistics** : 출석 통계 정보를 반환할 때 사용
totalAttendances: 총 정기모임 횟수
totalAttended: 출석한 수
attendanceRate: 출석률

- **ResponseWeek** : 특정 주차의 정보를 반환할 때 사용
week: 주차 정보
expirationTime : 유효기간

- **WeekDto** : 정기모임 주차 관련 데이터

## **Exception**
- **AttendanceExceptionHandler**: 출석 관련 예외 처리 핸들러

- **AttendanceCodeException**: 출석 코드 관련 예외 처리.
checkInAttendance 메서드에서 출석 코드가 유효하지 않은 경우 사용

- **ForbiddenException**: 사용자가 접근 권한이 없는 경우 발생하는 예외 처리.

- **ResourceNotFoundException**: 요청한 리소스를 찾을 수 없을 때 발생하는 예외 처리.

- **UnauthorizedException**: 인증되지 않은 접근 관련 예외 처리. 

## **Repository**

**AttendanceCodeRepository**: 출석 코드를 관리하는 JPA 레포
**MeetingRepository**: 정기모임 관련 정보를 관리하는 JPA 레포
**AttendanceRepository**: 출석 정보를 관리하는 JPA 레포
**PenaltyRepository**: 패널티 관련 정보를 관리하는 JPA 레포

## **service**

**AttendanceService**: 출석 관련 비즈니스 로직을 처리합니다. 출석 체크, 출석 코드 유효성 검사, 출석 기록 저장 등의 기능을 구현했습니다

**AttendanceStatisticsService**: 출석 통계 관련 비즈니스 로직을 처리합니다. 사용자의 출석 통계 정보를 계산하고 반환하는 기능을 제공합니다

**MeetingService**: 정기모임 정보를 관리하는 비즈니스 로직을 처리합니다. 정기모임 조회,  정기모임 관련 정보 반환 등의 기능을 제공합니다.

**PenaltyService**: 사용자에게 부여된 패널티 관련 비즈니스 로직을 처리합니다. 패널티 기록을 저장하고, 사용자에 대한 패널티 데이터를 관리합니다. 

**AttendanceCodeService**:  

## **Entity**

**Attendance**

**AttendanceCode**

**Meeting**

**Penalty**

**Week(enums)**

## 3. 메모
미완성 PR입니다.... 도와주세요
출석 통계처리 계산 부분에서 막혀서 check-in 부분을 주석처리로 일단 닫아놨습니다
출석 통계 부분 구현 후 월별 출석 통계 로직을 추가할 예정입니다

2024-07-14 06:25 UTC, jwnnoh requested changes
너무 고생많으셨습니다! 코멘트 확인 부탁드리고, 궁금한 점이 있으면 물어봐주시면 감사하겠습니다 🤗

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    public CommonResponse<String> recordPenalty(@RequestBody @Valid RequestPenalty requestPenalty, @RequestParam String email) {
명시적으로 쿼리 파라미터의 이름을 지정해주는 것을 추천드립니다!
```java
@RequestParam(value = "email")
```

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/dto/RequestAttendance.java
컨트롤러 단에 `valid` 방식으로 전달 값을 검증하는 방식으로 코드를 작성하였다면,
DTO 내의 변수들마다 일일히 어노테이션을 달아주실 필요는 없습니다!

또한, 클라이언트에서 전달받는 값의 의도치 않은 변조를 막기 위해, `Setter` 어노테이션은 사용하지 않는 것을 추천드립니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/dto/RequestPenalty.java
마찬가지로, 코멘트를 참고해 어노테이션을 수정해주시면 좋을 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/dto/RequestWeek.java
마찬가지로, 코멘트를 참고해 어노테이션을 수정해주시면 좋을 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/dto/ResponseAttendance.java
어떠한 어노테이션을 사용하실지 헷갈리신다면, record 클래스를 통한 DTO를 만들어보는 것은 어떨까요?
그렇다면 `Builder` 어노테이션 하나만 적용하여 보다 가독성이 높고 간결한 코드를 작성할 수 있을 것 같습니다.

[레코드 DTO를 사용해보자](https://velog.io/@phdljr/TIL-DTO-class%EB%A5%BC-record%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/dto/ResponseStatistics.java
각 메서드마다 set 메서드를 사용하는 방식은 추천드리지 않습니다.
만약 특정 값의 개별 입력을 위해 해당 방식으로 로직이 구현되어야 한다면,
메서드가 가지고 있는 의미를 보다 명확히 하기 위해 메서드명을 `set`보다는 `update` 방식으로 수정해주면 좋을 것 같아요!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/entity/Attendance.java
왜 엔티티 클래스에서 `setter`를 지양해야 할까요?

🤔 사용한 의도를 쉽게 파악하기 어렵습니다.
```java
Post post = new Post();
post.setId(1L);
post.setUserId("member1");
post.setTitle("제목입니다.");
post.setCont("내용입니다.");
```
위 코드의 경우 게시글 정보 Entity인 post를 set 메서드를 통해 값을 변경하는데 게시글의 값을 생성하는 구문인지, 변경하는 구문인지 정확한 의도를 파악하기 어렵죠?. 더군다나 객체의 내부 값이 많거나 복잡하다면, 더더욱 한눈에 알아보기 힘들 겁니다.

🧐 일관성을 유지하기 어렵습니다.
```java
public Post updatePost(Long id) {
    Post post = findById(id);
    post.setTitle("제목을 수정합니다.");
    post.setCont("내용을 수정합니다,");
    return post;
}
```
다음으로 위 코드의 경우 게시글을 변경하는 메소드인데, 
public으로 작성된 setter 메소드를 통해 어디서든 접근이 가능하기에 의도치 않게 post의 값을 변경하는 경우가 발생할 수 있습니다.
그렇다면 결국 post 객체의 일관성은 무너지게 되겠죠?

그렇다면 어떻게 해야할까요?
자세한 내용은 해당 블로그를 참고..>_<
[엔티티 클래스에 setter 어노테이션은 이제 그만!](https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0)

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/repository/AttendanceRepository.java
> +    List<Integer> findDistinctWeeks();
해당 로직은 굳이 쿼리문을 사용하지 않고 메서드명으로만 구현할 수 있을 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/repository/MeetingRepository.java
리포지토리 어노테이션은 일관성 있게 적용하는게 좋을 것 같습니다!
저의 의견은.. 모든 리포지토리에 어노테이션을 적용하지 않는 것을 추천드립니다 :)

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/PenaltyService.java
> +        penalty.setUser(user);
정적 팩토리 메서드 패턴을 통해 모든 내용을 담아 한번에 생성하는 방식이 좋을 것 같습니다!
```java
Penalty penalty = Penalty.of(requestPenalty.getDescription(), user);
```
[정팩메..어케써야할까?](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90#%EC%8B%A4%EB%AC%B4%EC%97%90%EC%84%9C_%EC%B0%BE%EC%95%84%EB%B3%B4%EB%8A%94_%EC%A0%95%EC%A0%81_%ED%8C%A9%ED%86%A0%EB%A6%AC_%EB%A9%94%EC%84%9C%EB%93%9C)

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/MeetingService.java
> +                        .build())
빌더 패턴을 DTO 내에 구현하면 코드의 가독성이 더욱 높아질 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/MeetingService.java
> +                .collect(Collectors.toList());
`toList()` 메서드를 통해 불변한 리스트를 반환하여 의도치 않은 값 변경을 막아주면 좋을 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +            if (Objects.equals(attendanceCode.getAttendanceCode(), requestAttendance.getAttendanceCode())) {
attendanceCode가 이미 `isPresent`를 통해 존재함이 확인되었는데, `Object.equals`를 사용하기보다는 `a.equals(b)`를 사용하는 방식이 좋을 것 같습니다!

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +                attendance.setWeek(attendanceCode.getWeek()); // Week 타입으로 설정
아래 코멘트를 참고해 개선하면 좋을 것 같습니다! >_<

2024-07-14 06:25 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceStatisticsService.java
> +        statistics.setAttendanceRate(attendanceRate);
아래 코멘트를 참고해 개선하면 좋을 것 같습니다! >_<

2024-07-14 06:55 UTC, jj0526 commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    @GetMapping("/statistics/{userId}") //특정 사용자 출석통계
토큰을 이용해서 본인의 출석률만 조회할 수 있도록 하면 좋을거같습니다!

2024-07-14 10:07 UTC, hyxklee reviewed
출석 로직 짜시느라 머리 아프실텐데 고생하셨습니다! 제 생각이랑 같이 고민해볼점 적어봤습니다! 참고해서 수정해주시면 감사하겠습니다!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    @GetMapping("/statistics/{userId}") //특정 사용자 출석통계
userId를 직접 입력받기 보다 저희 추가된 @CurrenUser 어노테이션 활용하면 JWT Token에서 현재 로그인된 사용자 인덱스를 불러올 수 있습니다! 해당 부분 참고하시면 좋을 거 같아요!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +        return CommonResponse.createSuccess("패널티가 기록되었습니다.");
문자열을 그대로 입력하기 보다는 상수로 관리하면 좋을 거 같아요!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/dto/RequestAttendance.java
여유가 되신다면 dto에 record를 적용해보시는 것도 좋을 거 같아요!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/dto/ResponseAttendance.java
> +public class ResponseAttendance {
response dto에는 validation을 하는 어노테이션이 필요하지 않을 것 같아요! request dto에서 validation을 한 후에 DB에 저장을 하고, 그 저장된 값을 반환할 때 사용하기 때문에 해당 어노테이션이 없어도 될 것 같습니다!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/entity/Attendance.java
개발 과정에서 setter를 목적에 의해 활용하는 것이 아니라면 닫아두는게 좋을 것 같아요!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/entity/Attendance.java
> +    private Long id;
변수명이 id이기 때문에 DB에 저장시 id로 저장되어 한 눈에 어떤 테이블의 id인지 구분하기 어렵습니다! 컬럼명을 엔티티명_id로 지정해주는 게 좋아요! 모든 엔티티에 해당하는 부분입니다.

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/entity/Meeting.java
> +    public Meeting() {}
생성자도 Lombok 어노테이션을 관리할 수 있어요! 참고자료 남기겠습니다!
https://velog.io/@code-10/롬복-AllNoArgsConstructor-제대로-알고-사용해보자

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +    public void checkInAttendance(RequestAttendance requestAttendance, String currentEmail) {
해당 부분도 @CurrentUser를 적용함에 따라 userId로 검색하는 쪽으로 수정해주시면 감사하겠습니다!

2024-07-14 10:07 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +    public void checkInAttendance(RequestAttendance requestAttendance, String currentEmail) {
현재 출석 로직이 requestAttendance에서 출석코드 id, 출석코드, userid, isAttend를 입력받아 서비스에서 출석코드 id를 불러와 dto의 출석코드와 대조 후 일치한다면 출석 정보를 저장하는 로직으로 이해를 했습니다! 하지만 저희 서비스의 요구사항에 따르면 사용자가 출석코드를 입력해 출석 요청을 보냈을 때 dto에는 사용자가 입력한 출석 코드가 담기고, 출석요청이 들어온 시간과 주차 정보를 비교해 해당 일자의 출석 코드를 불러와서 사용자가 입력한 코드와 일치하는지 확인 후 isAttend를 true 바꾸는 방식의 로직이 필요하다고 생각합니다! 일단 현재 생각나는 로직을 적어봤는데 해당 부분은 같이 얘기하면서 로직을 구체화해야할 것 같습니다! 혹시 제가 잘못 이해한 부분이 있다면 알려주시면 감사하겠습니다!!

2024-07-14 14:13 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    public CommonResponse<String> recordPenalty(@RequestBody @Valid RequestPenalty requestPenalty, @RequestParam String email) {
@RequestParam 어노테이션 사용시 참고하겠습니다 수정 완료했습니다👏

2024-07-14 14:28 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    public CommonResponse<String> recordPenalty(@RequestBody @Valid RequestPenalty requestPenalty, @RequestParam String email) {
@RequestParam 어노테이션 사용시 참고하겠습니다 👏 수정 완료했습니다

2024-07-14 16:13 UTC, jiixon reviewed
이미 리뷰가 많아서 안 달아주신 로직 부분에 대해서만 조금 썼습니다...! 코드가 그래도 정말 좋아진거같아요:) 이미 아시겠지만 ㅎㅎ PR 단위만 조금 줄인다면 더 좋을것 같습니다!! 고생하셨습니다.

2024-07-14 16:13 UTC, jiixon commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceStatisticsService.java
> +        userRepository.save(user);
유저에 대한 객체 변화가 있나요? 왜 save 하는지 궁금하네요!

2024-07-14 16:13 UTC, jiixon commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceStatisticsService.java
> +        userRepository.save(user);
이 로직에서 어떤걸 update하는지 잘 모르겠어요.. `user.setAttendanceRate(attendanceRate);`는 왜 주석 처리하셨나요?

2024-07-14 16:34 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +    public void checkInAttendance(RequestAttendance requestAttendance, String currentEmail) {
출석 인증 방법 관련해서는 더 고민이 필요할거 같습니다 @CurrenUser 어노테이션을 활용해서 출석로직, check-in 메서드 구현했습니다 !

2024-07-14 16:45 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +            if (Objects.equals(attendanceCode.getAttendanceCode(), requestAttendance.getAttendanceCode())) {
이미 null 체크를 수행한 상황이라 a.equals(b) 방식이 더 좋은거같습니다 ! 수정 완료했습니다

2024-07-14 16:50 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +            if (Objects.equals(attendanceCode.getAttendanceCode(), requestAttendance.getAttendanceCode())) {
validateAttendanceCode를 사용해서 각 기능을 2개의 메서드로 분리했습니다

2024-07-14 16:56 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/repository/AttendanceRepository.java
> +    List<Integer> findDistinctWeeks();
불필요한 쿼리문 삭제 완료했습니다!

2024-07-14 17:01 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/repository/MeetingRepository.java
JPA 레포에는 별도의 어노테이션이 필요하지 않다는 사실을 알았습니다 다음 JPA레포로 생성시 참고하겠습니다!

2024-07-14 17:18 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/dto/ResponseAttendance.java
> +public class ResponseAttendance {
해당 내용 참고하겠습니다 ! 불필요한 어노테이션 삭제했습니다

2024-07-14 17:18 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/dto/ResponseAttendance.java
> +public class ResponseAttendance {
해당 내용 참고하겠습니다 ! 불필요한 어노테이션 삭제했습니다

2024-07-14 17:24 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +        return CommonResponse.createSuccess("패널티가 기록되었습니다.");
예외처리 문장을 메서드로 지정하자는 의미일까요??

2024-07-14 17:28 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/entity/Attendance.java
> +    private Long id;
서로 다른 엔티티에서 중복된 칼럼명은 지양하겠습니다! 수정 완료했습니다

2024-07-14 17:34 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +    public void checkInAttendance(RequestAttendance requestAttendance, String currentEmail) {
@currentuser 활용해서 수정 완료했습니다

2024-07-14 17:46 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceStatisticsService.java
> +        userRepository.save(user);
attendanceRate라는 출석 통계가 User 객체에 반영되어야 변화가 있지만 현재 주석처리된 부분으로 인해서 아무런 업데이트가 이뤄지지 않은 상태입니다. 해당 라인은 오류로 인해서 주석처리 해놨었는데, 출석률 업데이트 로직 구현 완료 후 수정하겠습니다!

2024-07-15 02:09 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +        return CommonResponse.createSuccess("패널티가 기록되었습니다.");
메시지를 enum으로 관리하면 좋겠다는 뜻이었습니다!

2024-07-15 02:17 UTC, hyxklee commented on src/main/java/leets/weeth/domain/attendance/entity/Attendance.java
> +    private Long Attendance_id;
이렇게 변수 명을 직접 바꿔 구분하는 것도 좋지만 변수명은 id로 사용하고 @Column 어노테이션을 사용해 DB에 저장되는 이름만 변경하시는 방법이 일관성있는 개발에 더 좋을 거 같아요! JPA 어노테이션 정리된 블로그 남기고 가겠습니다
https://velog.io/@xeropise1/JPA-어노테이션-정리

2024-07-15 02:33 UTC, KoungQ requested changes
어려웠을텐데 개발하시느라 고생하셨습니다.
수정할 부분이 있으니 수정한 후 연락 부탁드립니다.

2024-07-15 02:33 UTC, KoungQ commented on src/main/java/leets/weeth/domain/attendance/exception/AttendanceExceptionHandler.java
> +}
Exception 캐치하는 로직은 이미 글로벌에 존재합니다.
그리고 ResponseEntity로 응답을 보낼 시 CommonResponse로 응답 객체를 통일하는 것에 어긋납니다.
Custom Exception은 저번에 회의에 말씀드린대로 global - common - exception - cumstom에 정의해주시고 ExceptionType 안에 enum 메세지 선언하시면 알아서 탐지해줄겁니다.

2024-07-15 02:33 UTC, KoungQ commented on src/main/java/leets/weeth/domain/attendance/entity/Meeting.java
> +    public Meeting() {}
Meeting이란 테이블은 ERD에 없었는데 지훈씨가 생각했을 때 필요한 테이블이라서 만드신건가요??
만약 그렇다면 팀원들과의 소통이 필요했을 것 같습니다.

2024-07-20 14:31 UTC, jwnnoh reviewed
고생하셨습니다! 궁금한 점이 있어서 코멘트 남겼으니, 확인 부탁드립니다!

2024-07-20 14:31 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    @PreAuthorize("hasRole('ROLE_USER') or hasRole('ROLE_ADMIN')")
해당 부분은 `Spring Security`에서 설정해주는 편은 어떨까요..?

2024-07-20 14:31 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/entity/AttendanceCode.java
> +    private String attendanceCode;
Attendance 객체에 attendanceCode가 있는데 해당 클래스가 별도로 있는 이유가 있을까요?

2024-07-20 14:31 UTC, jwnnoh commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +        ResponseAttendance responseDto = new ResponseAttendance();
해당 DTO도 매개변수를 개별적으로 서비스 로직에서 설정해주는 것 보다는, 빌더 또는 생성자를 통해 새로운 객체를 생성해주는 편이 좋지 않을까요?

2024-07-21 01:45 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/entity/AttendanceCode.java
> +    private String attendanceCode;
불필요한 패키지 삭제 완료했습니다 !

2024-07-21 01:46 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/controller/AttendanceController.java
> +    @PreAuthorize("hasRole('ROLE_USER') or hasRole('ROLE_ADMIN')")
@PreAuthorize 삭제 완료하여 Spring Security에서 경로 접속 권한 설정하도록 했습니다

2024-07-22 01:04 UTC, huncozyboy commented on src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
> +        ResponseAttendance responseDto = new ResponseAttendance();
응답 DTO 빌더패턴으로 적용했습니다 !

2024-07-22 04:10 UTC, hyxklee approved these changes
고생하셨습니다!

2024-07-22 04:27 UTC, jwnnoh approved these changes
고생하셨습니다!! 수고 많으셨어요 😄

2024-07-22 06:56 UTC, KoungQ approved these changes

2024-07-22 08:55 UTC, merged